// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logging.proto

package logging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ttl                  int32    `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c8ad1e4de00dd2b, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Log) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Log) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *Log) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Log) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type LogList struct {
	Logs                 []*Log   `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogList) Reset()         { *m = LogList{} }
func (m *LogList) String() string { return proto.CompactTextString(m) }
func (*LogList) ProtoMessage()    {}
func (*LogList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c8ad1e4de00dd2b, []int{1}
}

func (m *LogList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogList.Unmarshal(m, b)
}
func (m *LogList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogList.Marshal(b, m, deterministic)
}
func (m *LogList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogList.Merge(m, src)
}
func (m *LogList) XXX_Size() int {
	return xxx_messageInfo_LogList.Size(m)
}
func (m *LogList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogList.DiscardUnknown(m)
}

var xxx_messageInfo_LogList proto.InternalMessageInfo

func (m *LogList) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type LogRequest struct {
	Log                  *Log     `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c8ad1e4de00dd2b, []int{2}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type LogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c8ad1e4de00dd2b, []int{3}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Log)(nil), "logging.Log")
	proto.RegisterType((*LogList)(nil), "logging.LogList")
	proto.RegisterType((*LogRequest)(nil), "logging.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "logging.LogResponse")
}

func init() { proto.RegisterFile("logging.proto", fileDescriptor_9c8ad1e4de00dd2b) }

var fileDescriptor_9c8ad1e4de00dd2b = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4a, 0x44, 0x21,
	0x10, 0x87, 0x33, 0xf7, 0x0f, 0x3b, 0xdb, 0x46, 0x58, 0x84, 0x44, 0x84, 0x78, 0x75, 0xa0, 0xd8,
	0x8b, 0xd3, 0x2b, 0x74, 0xe9, 0xd5, 0xe9, 0x09, 0x2a, 0x86, 0x41, 0x70, 0xcf, 0x9c, 0xd4, 0xb6,
	0xd7, 0x0f, 0x75, 0x23, 0x4e, 0x77, 0xf3, 0xfb, 0xe6, 0x73, 0x1c, 0x85, 0x5d, 0x60, 0x22, 0x3f,
	0xd2, 0x7e, 0x8a, 0x9c, 0x59, 0xad, 0x4f, 0xd1, 0x7e, 0x83, 0x74, 0x4c, 0xea, 0x16, 0x56, 0x1c,
	0x3d, 0xf9, 0x51, 0x0b, 0x23, 0xba, 0xcd, 0x70, 0x4a, 0x85, 0x27, 0x8c, 0x47, 0x8c, 0xfa, 0xbc,
	0xf1, 0x96, 0xd4, 0x15, 0xc8, 0xc0, 0xa4, 0x65, 0x85, 0xa5, 0x54, 0xf7, 0xb0, 0xc9, 0xfe, 0x80,
	0x29, 0xbf, 0x1d, 0x26, 0xbd, 0x30, 0xa2, 0x93, 0xc3, 0x1f, 0x28, 0x7e, 0xce, 0x41, 0x2f, 0x8d,
	0xe8, 0x96, 0x43, 0x29, 0xed, 0x23, 0xac, 0x1d, 0x93, 0xf3, 0x29, 0x2b, 0x03, 0x8b, 0xc0, 0x94,
	0xb4, 0x30, 0xb2, 0xdb, 0xf6, 0x17, 0xfb, 0xdf, 0x55, 0x1d, 0xd3, 0x50, 0x3b, 0xf6, 0x09, 0xa0,
	0x04, 0xfc, 0xfc, 0xc2, 0x94, 0xd5, 0x43, 0xbb, 0xbc, 0x6c, 0xfa, 0x5f, 0x2f, 0x0d, 0xbb, 0x83,
	0x6d, 0xb5, 0xd3, 0xc4, 0x63, 0xc2, 0xfe, 0x05, 0x2e, 0x5d, 0x53, 0x5e, 0x31, 0x1e, 0xfd, 0x07,
	0xaa, 0xbe, 0x3d, 0xfa, 0x7a, 0x76, 0xb4, 0x0d, 0xbf, 0xbb, 0x99, 0xc3, 0x36, 0xc3, 0x9e, 0xbd,
	0xaf, 0xea, 0xc7, 0x3d, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xab, 0xa9, 0xd5, 0x80, 0x49, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggingServiceClient is the client API for LoggingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggingServiceClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type loggingServiceClient struct {
	cc *grpc.ClientConn
}

func NewLoggingServiceClient(cc *grpc.ClientConn) LoggingServiceClient {
	return &loggingServiceClient{cc}
}

func (c *loggingServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggingServiceServer is the server API for LoggingService service.
type LoggingServiceServer interface {
	Log(context.Context, *LogRequest) (*LogResponse, error)
}

func RegisterLoggingServiceServer(s *grpc.Server, srv LoggingServiceServer) {
	s.RegisterService(&_LoggingService_serviceDesc, srv)
}

func _LoggingService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoggingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logging.LoggingService",
	HandlerType: (*LoggingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _LoggingService_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logging.proto",
}
